# Generated by Django 5.1.6 on 2025-03-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=20)),
                ('jersey_number', models.IntegerField()),
                ('mathch', models.IntegerField()),
                ('goal', models.IntegerField()),
                ('yellowcard', models.IntegerField()),
                ('redcard', models.IntegerField()),
            ],
        ),
    ]
