# Generated by Django 5.1.6 on 2025-03-02 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='jersey_number',
            new_name='jersey_no',
        ),
    ]
