# Generated by Django 5.1.6 on 2025-03-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_losses_teamstanding_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstanding',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
