# Generated by Django 5.1.5 on 2025-03-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_teamplayers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamPlayers',
            new_name='BengaluruTeamPlayers',
        ),
    ]
