# Generated by Django 5.1.5 on 2025-03-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_keralateamplayers_mohammedanteamplayers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MohunBaganTeamPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=20)),
                ('mathch', models.IntegerField()),
                ('goal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MumbaiTeamPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=20)),
                ('mathch', models.IntegerField()),
                ('goal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NorthEastTeamPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=20)),
                ('mathch', models.IntegerField()),
                ('goal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OdishaTeamPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=20)),
                ('mathch', models.IntegerField()),
                ('goal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PunjabTeamPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=20)),
                ('mathch', models.IntegerField()),
                ('goal', models.IntegerField()),
            ],
        ),
    ]
