# Generated by Django 5.1.6 on 2025-03-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_teamstanding_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamstanding',
            old_name='image',
            new_name='img',
        ),
    ]
