# Generated by Django 5.1.6 on 2025-03-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_rename_image_teamstanding_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='bengaluruteamplayers',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='beng_pl/'),
        ),
    ]
