# Generated by Django 5.1.6 on 2025-03-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_eastbengalteamplayers_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goateamplayers',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='goa_pl/'),
        ),
        migrations.AlterField(
            model_name='hyderabadteamplayers',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='hyd_pl/'),
        ),
        migrations.AlterField(
            model_name='jamshedpurteamplayers',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='jams_pl/'),
        ),
        migrations.AlterField(
            model_name='keralateamplayers',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='ker_pl/'),
        ),
        migrations.AlterField(
            model_name='mohammedanteamplayers',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='moha_pl/'),
        ),
        migrations.AlterField(
            model_name='mohunbaganteamplayers',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='mohu_pl/'),
        ),
        migrations.AlterField(
            model_name='mumbaiteamplayers',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='mum_pl/'),
        ),
        migrations.AlterField(
            model_name='northeastteamplayers',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='ne_pl/'),
        ),
        migrations.AlterField(
            model_name='odishateamplayers',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='odis_pl/'),
        ),
        migrations.AlterField(
            model_name='punjabteamplayers',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='punj_pl/'),
        ),
    ]
