# Generated by Django 5.1.6 on 2025-03-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_goateamplayers_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='players/'),
        ),
    ]
