# Generated by Django 5.1.6 on 2025-03-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_players_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='club',
            field=models.ImageField(blank=True, null=True, upload_to='club_img/'),
        ),
    ]
